baseURL = 'https://panhaoneo.github.io/'
languageCode = 'en-us'
title = 'Pans WZ'
theme = ["archie","hugo-shortcode-timeline"]
author = 'Leo Pan'

sectionPagesMenu = "main"

[params]
subtitle = "less,but diff"
noindex = false
truncate = false

[params.theme]
# palette = "base16-dark" apprentice, base16-dark, base16-light, dracula, gruvbox-dark, gruvbox-light, material, papercolor-dark, papercolor-light, solarized-dark, solarized-light, tender, tokyo-night-dark, tokyo-night-light, windows-95 and windows-95-light. The default is base16-dark.
# palette = "base16-light"

# Sidebar: about/bio
[params.about]
title = "something a blog"
description = "Recording,Writing,Reading"
logo = "images/rice.svg"


[[menu.main]]
  identifier = "about"
  name = "about"
  url = "/about/"
  weight = 1
[[menu.main]]
  identifier = "health"
  name = "health"
  url = "/health/"
  weight = 9
[[menu.main]]
  identifier = "now"
  name = "now"
  url = "/now/"
  weight = 8
[[menu.main]]
  identifier = "diary"
  name = "diary"
  url = "/diary/"
  weight = 10
[[menu.main]]
  identifier = "posts"
  name = "posts"
  url = "/posts/"
  weight = 8

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      [markup.goldmark.extensions.cjk]
        eastAsianLineBreaks = false
        enable = false
        escapedSpace = false
      [markup.goldmark.extensions.typographer]
        apostrophe = '&rsquo;'
        disable = false
        ellipsis = '&hellip;'
        emDash = '&mdash;'
        enDash = '&ndash;'
        leftAngleQuote = '&laquo;'
        leftDoubleQuote = '&ldquo;'
        leftSingleQuote = '&lsquo;'
        rightAngleQuote = '&raquo;'
        rightDoubleQuote = '&rdquo;'
        rightSingleQuote = '&rsquo;'
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      wrapStandAloneImageWithinParagraph = true
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = true
  # Table of contents
  # Add toc = true to content front matter to enable
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'xcode'
    tabWidth = 2

